modLoader="javafml"
loaderVersion="[36.0,)"
credits="vincentmet"
license="All Rights Reserved"
[[mods]]
modId="customquests"
version="1.16.5-2.0.0"
displayName="Custom Quests"
description='''
Quests!!!
'''